name: Pull request Testing CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout lastest code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Use Node.js 20 to build
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Cache Node Modules
      id: cache-node-modules
      uses: actions/cache@v4
      with:
         path: ./node_modules
         key: node-modules-${{ runner.os }}-node-${{ hashFiles('./package.json') }}

    - name: Install Node Packages
      if: steps.cache-node-modules.outputs.cache-hit == ''
      run: npm install

    - name: Build docs
      run: npm run docs:build --if-present