name: Deploy Docs lastest to Server

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout lastest code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Use Node.js 20 to build
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Cache Node Modules
      id: cache-node-modules
      uses: actions/cache@v4
      with:
         path: ./node_modules
         key: node-modules-${{ runner.os }}-node-${{ hashFiles('./package.json') }}

    - name: Install Node Packages
      if: steps.cache-node-modules.outputs.cache-hit == ''
      run: npm install

    - name: Build docs
      run: npm run docs:build --if-present

    - name: Deploy package to ArkStation
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      if: ${{ success() }}
      with:
        host: ${{ secrets.DC_HOST }}
        user: ${{ secrets.DC_USER }}
        key: ${{ secrets.DC_PRIVATE_KEY }}
        connect_timeout: 10s
        first_ssh: |
          rm -rf /root/caddy-sites/source/html-docs/dist
        scp: |
          ./dist => /root/caddy-sites/source/html-docs/
        last_ssh: |
          sudo systemctl reload caddy.service

    - name: Deploy package to TreeHouse
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      if: ${{ success() }}
      with:
        host: ${{ secrets.DC_HOST_CN }}
        user: ${{ secrets.DC_USER }}
        key: ${{ secrets.DC_PRIVATE_KEY }}
        connect_timeout: 10s
        first_ssh: |
          sudo rm -rf /home/caddy-sites/source/doc/dist
        scp: |
          ./dist => /home/caddy-sites/source/doc/
        last_ssh: |
          sudo systemctl reload caddy.service
